from __future__ import annotations

from copy import deepcopy
from typing import Any, Dict, List


INDICATOR_CATEGORIES: List[Dict[str, str]] = [
    {"id": "quote", "label": "基础行情", "description": "价格、成交、换手和市值，决定股票池与流动性底线。"},
    {"id": "technical", "label": "技术强弱", "description": "RPS、均线、MACD、KDJ、平台形态等本地 K 线计算指标。"},
    {"id": "capital_flow", "label": "资金流向", "description": "主力净额、净流入和大小单结构，用来确认资金是否回流。"},
    {"id": "theme", "label": "题材行业", "description": "同花顺概念/行业成分以及基于成分股宽度计算的题材热度。"},
    {"id": "event", "label": "事件异动", "description": "涨跌停、炸板、龙虎榜和游资等低覆盖但高信息密度事件。"},
    {"id": "chips", "label": "筹码成本", "description": "筹码胜率、成本分布和潜在抛压，用来观察位置阻力。"},
    {"id": "risk", "label": "风险过滤", "description": "ST、停牌、涨幅过热、换手过热和异常事件风险。"},
    {"id": "market", "label": "市场环境", "description": "市场宽度、指数趋势和涨跌停温度，用来判断策略是否顺风。"},
]


INDICATORS: List[Dict[str, Any]] = [
    {
        "id": "latest_price",
        "name": "最新价",
        "category_id": "quote",
        "status": "active",
        "source": "Tushare 实时日线 / 本地历史 K 线",
        "formula": "优先取当日行情快照 latest_price，缺失时取最新历史 K 线 close。",
        "description": "用于过滤过低价格和展示当前交易位置。",
        "usage": ["filter", "display"],
        "default_missing_policy": "skip",
        "analysis_ready": True,
    },
    {
        "id": "amount",
        "name": "成交额",
        "category_id": "quote",
        "status": "active",
        "source": "Tushare 实时日线 / 历史 K 线",
        "formula": "当日快照 amount，缺失时取最新历史 K 线 amount。",
        "description": "衡量流动性，低成交额股票容易滑点大、信号失真。",
        "usage": ["filter", "score"],
        "default_missing_policy": "skip",
        "analysis_ready": True,
    },
    {
        "id": "turnover_rate",
        "name": "换手率",
        "category_id": "quote",
        "status": "active",
        "source": "Tushare daily_basic / 历史 K 线",
        "formula": "优先取 daily_basic.turnover_rate，缺失时取历史 K 线 turn。",
        "description": "衡量筹码交换强度，过低代表不活跃，过高可能代表分歧或过热。",
        "usage": ["filter", "risk", "score"],
        "default_missing_policy": "allow",
        "analysis_ready": True,
    },
    {
        "id": "volume_ratio",
        "name": "量比",
        "category_id": "quote",
        "status": "active",
        "source": "Tushare daily_basic / 本地 K 线估算",
        "formula": "优先取 daily_basic.volume_ratio；为空时用最新成交量 / 前 20 根成交量均值。",
        "description": "判断当前成交是否明显放大，是右侧突破和资金确认的重要指标。",
        "usage": ["filter", "score", "interaction"],
        "default_missing_policy": "allow",
        "analysis_ready": True,
    },
    {
        "id": "float_market_value",
        "name": "流通市值",
        "category_id": "quote",
        "status": "active",
        "source": "Tushare daily_basic / 快照估算",
        "formula": "优先使用 daily_basic.circ_mv 归一化后的流通市值，缺失时由流通股本和价格估算。",
        "description": "控制股票规模，避免过小或过大的标的进入同一套策略。",
        "usage": ["filter"],
        "default_missing_policy": "allow",
        "analysis_ready": True,
    },
    {
        "id": "rps20",
        "name": "RPS20",
        "category_id": "technical",
        "status": "active",
        "source": "本地历史 K 线",
        "formula": "按最近 20 日收益率在全市场排序并映射到 0-100。",
        "description": "短期相对强度，适合寻找强于市场的趋势股。",
        "usage": ["filter", "score", "sort"],
        "default_missing_policy": "skip",
        "analysis_ready": True,
    },
    {
        "id": "rps60",
        "name": "RPS60",
        "category_id": "technical",
        "status": "active",
        "source": "本地历史 K 线",
        "formula": "按最近 60 日收益率在全市场排序并映射到 0-100。",
        "description": "中期相对强度，比 RPS20 更稳定。",
        "usage": ["filter", "score", "sort"],
        "default_missing_policy": "skip",
        "analysis_ready": True,
    },
    {
        "id": "macd_state",
        "name": "MACD 状态",
        "category_id": "technical",
        "status": "active",
        "source": "本地历史 K 线 / Tushare stk_factor",
        "formula": "DIF、DEA 和 0 轴关系；平台/趋势模式中可设为必须或加分。",
        "description": "确认动能是否改善，避免弱势反抽被误判为突破。",
        "usage": ["filter", "score", "interaction"],
        "default_missing_policy": "allow",
        "analysis_ready": True,
    },
    {
        "id": "platform_range",
        "name": "平台振幅",
        "category_id": "technical",
        "status": "active",
        "source": "本地历史 K 线",
        "formula": "平台窗口内最高价 / 最低价 - 1，或按收盘价区间计算。",
        "description": "衡量横盘收敛程度，越小越接近蓄势平台。",
        "usage": ["filter", "score"],
        "default_missing_policy": "skip",
        "analysis_ready": True,
    },
    {
        "id": "platform_breakout_clearance",
        "name": "突破上沿距离",
        "category_id": "technical",
        "status": "active",
        "source": "本地历史 K 线",
        "formula": "最新收盘价 / 平台上沿 - 1。",
        "description": "判断是否刚刚有效站上平台上沿，也控制追高距离。",
        "usage": ["filter", "score", "interaction"],
        "default_missing_policy": "skip",
        "analysis_ready": True,
    },
    {
        "id": "platform_setup_distance_to_high",
        "name": "距平台上沿",
        "category_id": "technical",
        "status": "active",
        "source": "本地历史 K 线",
        "formula": "平台上沿 / 最新收盘价 - 1。",
        "description": "平台临界模式的核心位置指标，越接近上沿越值得观察。",
        "usage": ["filter", "score", "interaction"],
        "default_missing_policy": "skip",
        "analysis_ready": True,
    },
    {
        "id": "main_net_amount",
        "name": "主力净额",
        "category_id": "capital_flow",
        "status": "available",
        "source": "Tushare moneyflow",
        "formula": "大单与超大单买入金额 - 卖出金额，按本地 moneyflow 字段归一。",
        "description": "判断主动资金是否回流，适合做突破和平台临界的确认项。",
        "usage": ["score", "interaction"],
        "default_missing_policy": "neutral",
        "analysis_ready": False,
    },
    {
        "id": "net_mf_amount",
        "name": "资金净流入",
        "category_id": "capital_flow",
        "status": "available",
        "source": "Tushare moneyflow",
        "formula": "全口径买入金额 - 卖出金额。",
        "description": "辅助确认资金方向，和主力净额一起判断资金质量。",
        "usage": ["score"],
        "default_missing_policy": "neutral",
        "analysis_ready": False,
    },
    {
        "id": "topic_count",
        "name": "题材数",
        "category_id": "theme",
        "status": "available",
        "source": "Tushare ths_member",
        "formula": "统计股票关联的同花顺概念/行业成分数量。",
        "description": "只表示股票挂在哪些题材里，不直接代表题材强弱。",
        "usage": ["display", "score"],
        "default_missing_policy": "neutral",
        "analysis_ready": False,
    },
    {
        "id": "topic_heat",
        "name": "题材热度",
        "category_id": "theme",
        "status": "planned",
        "source": "ths_member + 当日行情 + 涨跌停",
        "formula": "对股票所属题材的成分股上涨比例、RPS 高分股数量、涨停数量和成交额扩张做综合评分。",
        "description": "判断个股是否站在活跃主线上，是 A 股策略里很有价值的联动指标。",
        "usage": ["score", "interaction", "sort"],
        "default_missing_policy": "neutral",
        "analysis_ready": False,
    },
    {
        "id": "theme_limit_count",
        "name": "题材涨停数",
        "category_id": "theme",
        "status": "planned",
        "source": "ths_member + Tushare limit_list_d",
        "formula": "统计股票所属题材内最近交易日涨停成分股数量。",
        "description": "衡量题材短线爆发力，适合接力和题材共振策略。",
        "usage": ["score", "interaction"],
        "default_missing_policy": "neutral",
        "analysis_ready": False,
    },
    {
        "id": "limit_event",
        "name": "涨跌停 / 炸板",
        "category_id": "event",
        "status": "available",
        "source": "Tushare limit_list_d",
        "formula": "读取最近涨停、跌停或炸板事件及开板次数、封单金额。",
        "description": "低覆盖事件指标。出现时信息密度很高，缺失通常代表普通交易日。",
        "usage": ["risk", "score", "interaction"],
        "default_missing_policy": "neutral",
        "analysis_ready": False,
    },
    {
        "id": "top_list_net_amount",
        "name": "龙虎榜净额",
        "category_id": "event",
        "status": "available",
        "source": "Tushare top_list / top_inst / hm_detail",
        "formula": "取最近龙虎榜或游资明细中的净买入金额。",
        "description": "短线资金偏好指标，只在上榜股票中出现。",
        "usage": ["score", "interaction", "risk"],
        "default_missing_policy": "neutral",
        "analysis_ready": False,
    },
    {
        "id": "cyq_winner_rate",
        "name": "筹码胜率",
        "category_id": "chips",
        "status": "available",
        "source": "Tushare cyq_perf",
        "formula": "获利筹码占比，来自 Tushare 筹码分布性能接口。",
        "description": "观察筹码位置与潜在抛压，适合趋势与低阻力策略。",
        "usage": ["score", "risk"],
        "default_missing_policy": "neutral",
        "analysis_ready": False,
    },
    {
        "id": "cost_50pct",
        "name": "中位成本",
        "category_id": "chips",
        "status": "available",
        "source": "Tushare cyq_perf",
        "formula": "筹码分布中 50% 成本位置。",
        "description": "用当前价和中位成本的距离观察压力与支撑。",
        "usage": ["score", "risk"],
        "default_missing_policy": "neutral",
        "analysis_ready": False,
    },
    {
        "id": "is_st",
        "name": "ST 状态",
        "category_id": "risk",
        "status": "active",
        "source": "股票基础信息 / 历史 K 线",
        "formula": "股票名或历史数据中的 ST 标记。",
        "description": "默认风险过滤项，通常不进入普通策略。",
        "usage": ["filter", "risk"],
        "default_missing_policy": "allow",
        "analysis_ready": True,
    },
    {
        "id": "overheat_risk",
        "name": "过热风险",
        "category_id": "risk",
        "status": "active",
        "source": "本地计算",
        "formula": "结合近 5/10 日涨幅、当前涨幅、换手率和距均线偏离度。",
        "description": "识别已经脱离买点或分歧过大的候选股。",
        "usage": ["risk", "interaction"],
        "default_missing_policy": "neutral",
        "analysis_ready": True,
    },
    {
        "id": "market_breadth",
        "name": "市场宽度",
        "category_id": "market",
        "status": "available",
        "source": "本地历史 K 线 / 市场环境表",
        "formula": "统计全市场上涨比例、涨跌停温度和指数趋势后综合评分。",
        "description": "判断策略环境是否顺风，适合作为仓位或信号阈值调节项。",
        "usage": ["context", "risk"],
        "default_missing_policy": "neutral",
        "analysis_ready": False,
    },
]


SIGNAL_MODE_TEMPLATES: List[Dict[str, Any]] = [
    {
        "id": "platform_breakout_core",
        "name": "平台突破",
        "base_signal_mode": "platform_breakout",
        "description": "保留现有平台突破骨架，强调平台收敛、首次突破和放量确认。",
        "note": "适合右侧确认，不追求题材过滤时使用。",
        "rule_groups": [
            {
                "id": "must",
                "label": "必须满足",
                "rules": [
                    {
                        "id": "platform_is_tight",
                        "name": "平台足够收敛",
                        "kind": "filter",
                        "indicator_ids": ["platform_range"],
                        "expression": "平台振幅 <= 策略设置上限",
                        "effect": {"type": "filter", "value": "must"},
                        "missing_policy": "skip",
                        "editable": True,
                    },
                    {
                        "id": "first_breakout",
                        "name": "首次有效突破",
                        "kind": "filter",
                        "indicator_ids": ["platform_breakout_clearance"],
                        "expression": "最新收盘价站上平台上沿，且不是已经远离平台的旧突破",
                        "effect": {"type": "filter", "value": "must"},
                        "missing_policy": "skip",
                        "editable": True,
                    },
                ],
            },
            {
                "id": "score",
                "label": "加分确认",
                "rules": [
                    {
                        "id": "volume_confirms_breakout",
                        "name": "放量确认突破",
                        "kind": "interaction",
                        "indicator_ids": ["platform_breakout_clearance", "volume_ratio"],
                        "expression": "突破上沿距离达标，并且量比 >= 设定阈值",
                        "effect": {"type": "score", "value": 18},
                        "missing_policy": "neutral",
                        "editable": True,
                    }
                ],
            },
        ],
    },
    {
        "id": "theme_resonance_breakout",
        "name": "题材共振突破",
        "base_signal_mode": "platform_breakout",
        "description": "平台突破叠加题材热度与量能确认，优先找站在活跃主线里的突破。",
        "note": "等题材热度接入分析后，这个模板会成为 A 股特色主线策略。",
        "rule_groups": [
            {
                "id": "base",
                "label": "形态底座",
                "rules": [
                    {
                        "id": "platform_breakout_base",
                        "name": "平台突破底座",
                        "kind": "filter",
                        "indicator_ids": ["platform_range", "platform_breakout_clearance"],
                        "expression": "平台收敛，并且最新价有效突破平台上沿",
                        "effect": {"type": "filter", "value": "must"},
                        "missing_policy": "skip",
                        "editable": True,
                    }
                ],
            },
            {
                "id": "interaction",
                "label": "联动因子",
                "rules": [
                    {
                        "id": "theme_volume_breakout",
                        "name": "题材放量共振",
                        "kind": "interaction",
                        "indicator_ids": ["platform_breakout_clearance", "volume_ratio", "topic_heat"],
                        "expression": "突破上沿达标，并且量比放大，并且题材热度 >= 70",
                        "effect": {"type": "score", "value": 22},
                        "missing_policy": "neutral",
                        "editable": True,
                    },
                    {
                        "id": "theme_limit_boost",
                        "name": "同题材涨停助攻",
                        "kind": "interaction",
                        "indicator_ids": ["topic_heat", "theme_limit_count"],
                        "expression": "题材热度升温，且同题材存在涨停成分股",
                        "effect": {"type": "score", "value": 12},
                        "missing_policy": "neutral",
                        "editable": True,
                    },
                ],
            },
            {
                "id": "risk",
                "label": "风险扣分",
                "rules": [
                    {
                        "id": "breakout_overheat",
                        "name": "突破过热扣分",
                        "kind": "interaction",
                        "indicator_ids": ["overheat_risk", "turnover_rate"],
                        "expression": "近 5/10 日涨幅偏高，或换手率进入过热区间",
                        "effect": {"type": "risk", "value": -12},
                        "missing_policy": "neutral",
                        "editable": True,
                    }
                ],
            },
        ],
    },
    {
        "id": "capital_return_setup",
        "name": "资金回流平台",
        "base_signal_mode": "platform_setup",
        "description": "平台临界叠加主力资金回流，寻找还没突破但已经有资金试探的标的。",
        "note": "偏观察池和盘中雷达，适合提前盯临界位。",
        "rule_groups": [
            {
                "id": "interaction",
                "label": "联动因子",
                "rules": [
                    {
                        "id": "setup_capital_return",
                        "name": "缩量平台后资金回流",
                        "kind": "interaction",
                        "indicator_ids": ["platform_setup_distance_to_high", "volume_ratio", "main_net_amount"],
                        "expression": "距离平台上沿足够近，量能温和恢复，主力净额转正",
                        "effect": {"type": "score", "value": 20},
                        "missing_policy": "neutral",
                        "editable": True,
                    }
                ],
            }
        ],
    },
    {
        "id": "low_resistance_trend",
        "name": "低阻力趋势",
        "base_signal_mode": "trend_resonance",
        "description": "趋势共振叠加筹码胜率与成本位置，寻找上方压力较轻的趋势股。",
        "note": "适合中短线趋势观察，不追求涨停事件。",
        "rule_groups": [
            {
                "id": "score",
                "label": "加分确认",
                "rules": [
                    {
                        "id": "trend_low_resistance",
                        "name": "趋势与筹码低阻力",
                        "kind": "interaction",
                        "indicator_ids": ["rps20", "cyq_winner_rate", "cost_50pct"],
                        "expression": "RPS 强，筹码胜率改善，当前价没有明显脱离中位成本",
                        "effect": {"type": "score", "value": 16},
                        "missing_policy": "neutral",
                        "editable": True,
                    }
                ],
            }
        ],
    },
]


def indicator_library() -> Dict[str, Any]:
    indicators = deepcopy(INDICATORS)
    categories = deepcopy(INDICATOR_CATEGORIES)
    signal_modes = deepcopy(SIGNAL_MODE_TEMPLATES)
    return {
        "categories": categories,
        "indicators": indicators,
        "signal_modes": signal_modes,
        "summary": {
            "category_count": len(categories),
            "indicator_count": len(indicators),
            "active_count": sum(1 for item in indicators if item["status"] == "active"),
            "available_count": sum(1 for item in indicators if item["status"] == "available"),
            "planned_count": sum(1 for item in indicators if item["status"] == "planned"),
            "signal_mode_count": len(signal_modes),
            "interaction_rule_count": sum(
                1
                for template in signal_modes
                for group in template["rule_groups"]
                for rule in group["rules"]
                if rule["kind"] == "interaction"
            ),
        },
    }
